### ISSUE TITLE
Python engine cmd error

### ISSUE THREAD

**Issue by denhartog** [nanobox-io/nanobox-engine-python#44]
"FAILED TO CLONING" should be singular "CLONE"

ON failure: nanobox run
    - Setting up directories and permissions...    - Cloning engine :
    
    ! FAILED TO CLONING HTTPS://GITHUB.COM/NANOBOX-IO/NANOBOX-ENGINE-PYTHONG.GIT !

**Comment by danhunsaker** [comment]
What is the `engine` set to in your `boxfile.yml`?

**Comment by denhartog** [comment]
engine: pythong; which of course is invalid. I thought it was curious nanobox even tried to proceed with a non-existent engine. Regardless, "cloning" should be "clone" and is a nanobox thing rather than a particular engine.

**Comment by sanderson** [comment]
@denhartog Engines can be pulled from anywhere, not just from the Nanobox engine repos. However, if a single-word engine name is provided, it assumes `nanobox-io/nanobox-engine-<name>` on github. But you can also use a local engine:

```
run.config:
  engine: ../some-local-dir
```

or a custom engine on github:

```
run.config:
  engine: ghuser/custom-repo
```

In regards to the wording of the error message, `FAILED TO` is generic text for all messages `CLONING ...` is the step that failed. So while the verbiage of the error message sounds incorrect, the context may explain why.

**Comment by denhartog** [comment]
All the same; thanks for the explanation. Excited to explore nanobox.io more!
